[project]
name = "datacontract-mcp"
version = "0.1.0"
description = "MCP server for data contracts"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.6.0",
    "pydantic>=2.0.0",
    "pyyaml>=6.0.1",
    "requests>=2.31.0",
    "duckdb>=0.9.2",
    "pandas>=2.1.0",
    "boto3>=1.34.0"
]

[project.scripts]
mcp-server-datacontract = "server:main"


[tool.uv]
dev-dependencies = [
    "pyright>=1.1.389",
    "ruff>=0.7.3"
]
